// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// The app's secrets already live in .env.local (Next.js loads it automatically,
// the Prisma CLI does not). Load it first — dotenv won't overwrite variables
// that are already set, so .env.local wins over .env, matching Next's order.
loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI only (migrate/studio/seed). Migrations can't run through Supabase's
    // pgbouncer pooler, so prefer the direct 5432 connection here. The app
    // runtime uses the pooled DATABASE_URL instead.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
